name: CI

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: lts/hydrogen
      - name: Install
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Test fixtures
        run: npm run test
      - name: Build Storybook
        run: npm run build
      - name: Build package
        run: ./bin/build-release.sh
      - name: Test package
        run: node tasks/test-package.js || exit 1
