name: CI

on:
  push:
    branches:
      - '**'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
      - name: Install
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Start Storybook
        run: npm start &
      - name: Run tests
        run: npm run test

  prototype-kit:
    name: Prototype kit integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
      - name: Install
        run: npm ci
      - name: Build package
        run: ./tasks/build-package.sh
      - name: Create prototype
        run: >
          mkdir prototype &&
          cd prototype &&
          npx govuk-prototype-kit create
      - name: Copy package
        run: >
          mkdir -p prototype/node_modules/@nationalarchives/frontend &&
          cp -fR package/* prototype/node_modules/@nationalarchives/frontend
      - name: Cat template
        run: cat prototype/app/views/index.html
      - name: Add imports to template
        run: >
          echo -e "{% from "nationalarchives/components/button/macro.njk" import tnaButton %}\n$(cat prototype/app/views/index.html)" > prototype/app/views/index.html &&
          echo -e "{% from "nationalarchives/components/header/macro.njk" import tnaHeader %}\n$(cat prototype/app/views/index.html)" > prototype/app/views/index.html
      - name: Cat template
        run: cat prototype/app/views/index.html
      - name: Add components to template
        run: >
          echo "{% block bodyEnd %}" >> prototype/app/views/index.html &&
          echo "{{ tnaButton({text:\"I am a button\",url:\"#\"}) }}" >> prototype/app/views/index.html &&
          echo "{{ tnaHeader({}) }}" >> prototype/app/views/index.html &&
          echo "{% endblock %}" >> prototype/app/views/index.html
      - name: Cat template
        run: cat prototype/app/views/index.html
      - name: Run prototype
        run: >
          cd prototype &&
          npm run dev &
