name: CI

on:
  push:
    branches:
      - '**'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
      - name: Install
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Start Storybook
        run: npm start &
      - name: Run tests
        run: npm run test
