name: Publish new release

on:
  release:
    types:
      - published

jobs:
  check:
    name: Pre-release checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check version numbers
        run: |
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          ./tasks/validate-version.sh $VERSION

  lint:
    runs-on: ubuntu-latest
    needs:
      - check
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/lint
  
  tests:
    runs-on: ubuntu-latest
    needs:
      - lint
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/tests

  prototype-kit:
    runs-on: ubuntu-latest
    needs:
      - check
      - lint
      - tests
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/prototype-kit-test

  publish-npm:
    name: Build package and publish to npm
    runs-on: ubuntu-latest
    needs:
      - check
      - prototype-kit
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          registry-url: https://registry.npmjs.org/
          scope: '@nationalarchives'
      - name: Install dependencies
        run: npm ci
      - name: Build package
        run: ./tasks/build-package.sh
      - name: Check npm credentials
        run: npm whoami
      - name: Publish to npm
        run: cd package && npm publish

  # notify-slack:
  #   runs-on: ubuntu-latest
  #   needs:
  #     - publish-npm
  #   steps:
  #   - uses: actions/checkout@v3
  #   - uses: rtCamp/action-slack-notify@v2
  #     env:
  #       SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
  #       SLACK_TITLE: "A deployment to ${{ github.head_ref || github.ref_name }} is imminent"