name: Publish new release

on:
  release:
    types:
      - published

jobs:
  publish-npm:
    name: Build package and publish to npm
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          registry-url: https://registry.npmjs.org/
          scope: '@nationalarchives'
      - name: Install dependencies
        run: npm ci
      - name: Check version numbers
        run: ./tasks/validate-version.sh
      - name: Build package
        run: ./tasks/build-package.sh
      - name: Check npm credentials
        run: npm whoami
      - name: Publish to npm
        run: cd package && npm publish
