name: Publish new release

on:
  release:
    types:
      - published

jobs:
  test:
    name: Run tests and lint checking
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
      - name: Check version numbers
        run: ./tasks/validate-version.sh
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Start Storybook
        run: npm start &
      - name: Run tests
        run: npm run test

  publish-npm:
    name: Publish
    needs: test
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          registry-url: https://registry.npmjs.org/
          scope: '@nationalarchives'
      - name: Install dependencies
        run: npm ci
      - name: Build package
        run: ./tasks/build-package.sh
      - name: Test package
        run: node tasks/test-package.js || exit 1
      - name: Check npm credentials
        run: npm whoami
      - name: Publish to npm
        run: cd package && npm publish
