name: Pull request

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - ready_for_review

jobs:
  lint:
    name: Run lint checking
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
  
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
      - name: Install dependencies
        run: npm ci
      - name: Build Storybook
        run: npm run build
      - name: Start Storybook
        run: npm start &
      - name: Run tests
        run: npm run test
        
  package:
    name: Test package
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
      - name: Install dependencies
        run: npm ci
      - name: Build package
        run: ./tasks/build-package.sh
      - name: Test package
        run: node tasks/test-package.js || exit 1

  chromatic:
    name: Upload to Chromatic
    runs-on: ubuntu-latest
    needs:
      - tests
      - package
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
      - name: Install dependencies
        run: npm ci
      - name: Build Storybook
        run: npm run build
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          storybookBuildDir: storybook
          exitZeroOnChanges: false
          onlyChanged: true
