name: CI

on:
  push:
    branches:
      - '**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/lint
      
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/tests

  prototype-kit:
    runs-on: ubuntu-latest
    needs:
      - lint
      - tests
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/prototype-kit-test
