name: CI

on:
  push:
    branches:
      - '**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Lint
        uses: ./.github/actions/lint

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Tests
        uses: ./.github/actions/tests

  test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Tests
        uses: ./.github/actions/test-build

  prototype-kit:
    runs-on: ubuntu-latest
    needs:
      - test-build
    steps:
      - uses: actions/checkout@v3
      - name: GOV.UK prototype kit test
        uses: ./.github/actions/prototype-kit-test
