name: CI

on:
  push:
    branches:
      - '**'

jobs:
  lint:
    uses: ./.github/workflows/_lint.yml
  
  tests:
    uses: ./.github/workflows/_tests.yml

  prototype-kit:
    needs:
      - lint
      - tests
    uses: ./.github/workflows/_prototype-kit-test.yml
